### PR TITLE
Main page (gopkg.in)

### PR DESCRIPTION
**Pull request by GeertJohan**

### CODE REVIEW

**Comment by GeertJohan** [comment]
Any update on this?

**Comment by GeertJohan** [comment]
ping

**Comment by ainar-g** [comment]
Four years later, will this be merged? I don't mean any disrespect, gopkg.in has become an important part of the Go ecosystem, but its main page still redirects to a blog post, which is at the very least odd for a project used by tens if not hundreds of thousands developers around the globe.

**Comment by GeertJohan** [comment]
Would still like to see this merged as well.

**Comment by niemeyer** [comment]
This has been standing here for too long, sorry about that. It's unlikely that this will get attention given the current direction of the go tool, so closing it.

**Pull request closed without merging**
